### ISSUE TITLE
Please rename the attributes to match the camelCase convention

### ISSUE THREAD

**Issue by urish** [bonnyr/wokwi-ds1820-custom-chip#19]
e.g. `deviceId` instead of `device_id`, `familyCode` instead of `family_code`, etc.

**Comment by bonnyr** [comment]
release v0.4.5 has been submitted to close this for external attributes. Need some more testing but should be ok

**Comment by urish** [comment]
Thank you! Should we update the public wokwi-board?

**Comment by bonnyr** [comment]
I believe so :)
